### ISSUE TITLE
关于健康检查一些疑问

### ISSUE THREAD

**Issue by Donghui0** [projecteru/citadel#1]
hi:
##### 应用发版时 能否做到 容器启动后 调用 after_start 脚本检查容器中应用是否已启动完毕. 如果启动完毕 则退出(状态码: 0), 如果探测应用启动过程中失败(状态码: != 0) 则此次发版以失败告终.  启动完毕并且启动成功后 则调用heathcheck 脚本进行健康检查探测, 如果探测成功 则依次启动其他容器, 否则以失败告终.

      疑问1:   healthcheck  是否等待 after_start 退出后再进行验证.
      疑问2:  after_start 是否有退出状态验证.
      疑问3:  healthcheck  是否允许脚本方法判断而非固定使用 HTTP.  比如应对 Java 工程中的 dubbo rpc 框架.

3ks

**Comment by tonicmuroq** [comment]
1. 分开的, 启动是这样的: `create`, `start`, `inspect` 检查是不是起来了, `run after_start`, healthcheck 跟这个是分开的, `after_start` 在 core 里做, healthcheck 在 agent 里做, 互相不知道

2. `after_start` 调用的 docker 的 `ContainerExecStart` API

3. 为了简单只在 agent 里实现了简单的 tcp 拨号验证连接和 http 请求验证应用, 如果有其他的欢迎 PR

**Comment by CMGS** [comment]
我补充一下

1. after_start 不是用于 healthcheck 这个目的的，主要是有些业务需要数据预热等需求，成功失败与否都会通过日志反馈出来。对于 healthcheck 而言，它是针对于单个容器状态进行检测，如果有使用类似于 ELB 一样的 proxy 则会通过这个状态来判断是否进行动态切流

2. 如我所说，after_start 的成功与否都会在日志中表现出来，可以参考[这里](https://github.com/projecteru2/core/blob/master/cluster/calcium/create_container.go#L184)，当然了如果有强制需要 after_start ，那么这里可以增加容器回收流程

3. TCP 的验证需要跟业务逻辑耦合，不如 HTTP 的来得简单，因此在 Agent 实现中我们暂时只实现了 HTTP 逻辑校验和 TCP 联通校验，针对这个可以根据自身的需求进行定制。对于我们来说，不是很希望平台层面的组件去关心业务的实现并去耦合其逻辑。

**Comment by Donghui0** [comment]
了解.  健康检查 其实指定脚本方式去判断就好了. 这样也无需关心具体判断逻辑 只管脚本的返回值来确定成功或失败.  另外, 应该没有累计次数吧. 比如像 k8s 的 successThreshold, failureThreshold. 重试多少次成功或失败才会认为其可用或不可用.

另外,  平滑升级的并发粒度可控么, 看 specs 中没有相关的参数控制. 比如初始粒度为1, 成功后可递增.

题外问下,  当初是基于什么原因考虑 把容器创建这些容器的操作放在了 core 而非 agent 上呢 ? 总感觉 core 应该轻量一些, 比如只管资源分配与调度 由 agent 来 watch 进行容器操作.

3ks

**Comment by timfeirg** [comment]
* 脚本检查如果不考虑安全性的话, 是挺通用的, 但是在 ENJOY 没有这个需求, 大多数 java 项目在 `app.yaml` 里声明一个健康检查的 url 就算搞定了, 对于 python web 项目, 直接用免费送的 tcp 健康检查甚至就足够了, 采用脚本健康检查的话, 还要求他们在项目里边加上一个带有 timeout 的 curl, 才能达到相同功能.
* 平滑升级是并发执行, 没有你说的粒度控制, 也没有那些复杂的滚动策略, 比如金丝雀部署. 平滑本身是靠健康检查来保证的.
* 创建容器的操作放到 agent 上, 对于 ERU 来说有什么好处来着? 乍看没什么特别的好处, 还增加了 agent <-> core 的通讯, 显得没有必要

**Comment by CMGS** [comment]
@Donghui0 我们的健康检查和 k8s 的出发点还是有些不同的。对 k8s 来说，它关注的是一个 Pod 意义上的 healthcheck，因此需要有这类检测冗余来满足最小服务单元 Pod 对外的稳定性。对于我们来说 Pod 是个逻辑上的机器组结构，最小服务单元就是容器本身，因此冗余并没太多存在的意义。

在实际生产中，上层应用看到的是一组容器来提供这一类服务，因此单个容器探测是否健康并不会对这一组容器行为造成太大影响，无外乎就是本来 1000个容器在支撑这个服务，而有一个临时被切走了流量变成只有999个容器在支撑了。当然具体生产过程中还会更加复杂，比如报警机制的反馈一类的。具体到冗余有没有必要，要根据不同生产来做不同的选择，就我们目前所支撑的业务来说，暂时没这个需求也就没动力去做了。

平滑升级这一块的颗粒度其实在实现上我们有过不少的争执，我个人是比较倾向于你所说的一次升级分批递增进行。但是同样受制于公司规模（2个公司的规模均在百台机器千个容器的水平），在这个 PaaS 层的实现（也就是 citadel 项目）中我们并没采用这种行为，完全基于全量升级和通过 healthcheck 来保证。对于 Core 的实现来说，多次调用 API 的行为结果是一致并且可预知的，如果将来有这个需要也能很方便的在 PaaS 层上自行组装并实现。

对于最后这个问题我得澄清下的是，包括 @timfeirg 也不是很理解这个上面的取舍。早期我们刚开始做 Eru 前身也就是 NBE 的时候就采用过 Core 下发 Agent 执行的架构，但这样会带来几个问题：

1. Agent 必须高可用，并且得有一个地方能准确的反馈其部署情况。同时在高压力情况下 Agent 的处理效率要足够高，不然就会造成 Node 不可限制的资源消耗增多，影响已经有的容器运行。
2. 对于 Core 而言，要么你需要对 Agent 的可用程度进行管理和维护，但这样一来整个 Core 就是带状态的了，大集群横向扩展会比较麻烦。一个 workaround 的方法是每个 Core 都有全量 Agent 的信息，但这样会造成近似于惊群效应。当然也可以把任务下发到 mq 一类的基础设施去执行，但这样一来首先这类基础设施也需要高可用，另外同样的关于系统状态一致性的获取和检测都是一件比较麻烦的事。我们希望 Eru 是旁路的，也就是说无论 Core-Agent 是否有问题都不应该影响现有的容器运行，而每多增加一个组件所需要花费在信息一致性上的成本就越高。
3. 安全性考虑，Agent 开放什么协议，开放什么端口，再去包装一层 Docker 的 API 是否有必要，这些也是需要权衡的。相比较之下 Core 目前只需要通过 https 直连 daemon，并不需要做太多其他操作还是要复杂了不少。简单可依赖，高可用可扩展是当时写 Eru2 的目的之一。

大概就是这 3 点，对于 Eru 来说逻辑层面上分了 PaaS 层（citadel）和 IaaS 层（Core），对于 Core 而言内部又分为调度和编排2个层面，互相是相互独立的。同时现在的结构当一个 Core 已经性能不够的时候完全可以通过 LVS-(CORE, CORE, CORE...) 这样的结构来进行扩展。至于 Agent 它只需要负责好自己的一亩三分地尽可能的不要对 Node 性能预估造成影响就可以了。

**Comment by Donghui0** [comment]
感谢 @CMGS  @timfeirg  的回复.
最后确认下, 平滑升级这块  假如应用集群规模64个容器, 那么同一时刻 并发启动64个容器, 与原有旧版本应用保持同步运行, 当健康检查全部通过或者等待最大时间 即erection_timeout  才会将旧版本容器全部关掉 或是健康检查失败 删除此次部署的容器.   那在erection_timeout 时间内  需要这个集群有一定的冗余空间.
还是说 这些容器绑定的资源和原容器是一样的?  应该是后者吧.  
那 ELB 的刷新 是什么时候做的?   只要容器确认健康 就会自动加到 ELB 中吧.  会优雅的移除旧版本的容器么?  先移除 ELB 中旧容器列表, 再移除容器.

3ks

**Comment by timfeirg** [comment]
是的, 平滑升级需要有相应的冗余, 冗余不够的话, 能成功多少成功多少, web 界面会给出日志提示

elb 刷新是 citadel 有一个 watch-etcd.service 常驻, 然后监听 eru-agent 的 etcd 下的数据, 看到容器健康了, 就更新到 elb 上.

**Comment by timfeirg** [comment]
我已经更新了平滑升级相关的文档.

感觉 after_start, before_stop 按理说是应该加上退出状态检查才算是一个完整的东西, 然后状态检查和报警似乎并不好做, 要做就得直接在 core 里做吧, 所以现在我又想鼓动去掉 after_start/before_stop 这个东西了 @tonicbupt @CMGS 

建议把这个 issue 里提到的一些设计思路相关的东西补充到白皮书以后再 close issue.

**Comment by CMGS** [comment]
补充了一点在 FAQ 里面 https://projecteru2.gitbooks.io/white-paper/content/FAQ.html

@timfeirg  @tonicbupt 你们看还需要有补充的没

**Comment by Donghui0** [comment]
其他感觉都很好. 唯一有些不爽的是 平滑迁移需要保证集群拥有足够剩余可用资源.  这样导致 当集群在高负载的时候 连发版都做不到. 比如 紧急 bug 修复.   或者是仍在旧版本容器 物理机启动相应的容器. 绑定资源也是旧版本容器资源. 这样也不需要额外的资源, 也少了资源的重新分配与回收.  毕竟, 集群的剩余资源应该是为了应对突发流量 所以感觉有些浪费. 虽然发版成功会将旧容器资源回收. (个人愚见)

所以, 还是比较倾向于 k8s 的 deployment rolling update.   不会给人感觉 集群资源利用率 忽上忽下的. (同为个人愚见)

3ks

**Comment by CMGS** [comment]
@Donghui0 这个是我们在 PaaS 层上的设计，实际对于 Core 而言并没这个逻辑。从我们生产情况来看，芒果TV和 ENJOY 都属于极端情况下「需要有 50%」冗余的业务，因此全量更新对我们来说是可以接受的，这也是 Citadel 对于更新逻辑如此设计的原因。至于和 K8S 的异同如果平台方能接受短期的资源波动我觉得还是可以接受吧，当时放弃 rolling update 的一个原因就是集群在某一个时间点上是不一致的，而且随着集群规模的增大这个不一致的存在时间也会越长。
